Micronaut supports automatically configuring http://www.jooq.org/[jOOQ] library for fluent, typesafe SQL query construction.

To configure jOOQ library you should first add `jooq` module to your classpath:

dependency:micronaut-jooq[groupId="io.micronaut.sql"]

You should then <<jdbc, configure one or many DataSources>>.
For each registered `DataSource`, Micronaut will configure the following jOOQ beans using api:configuration.jooq.JooqConfigurationFactory[]:

* link:{jooqapi}/org/jooq/Configuration.html[Configuration] - jOOQ `Configuration`
* link:{jooqapi}/org/jooq/DSLContext.html[DSLContext] - jOOQ `DSLContext`

If Spring transaction management is in use, it will additionally create the following beans :

* api:configuration.jooq.JooqExceptionTranslatorProvider[] for each `DataSource`
* api:configuration.jooq.SpringTransactionProvider[] for each Spring `PlatformTransactionManager`

== Programmatic transactions

For most applications, the recommended way to use jOOQ is inside Micronaut-managed transactions (for example via `@Transactional`).

If you need to execute jOOQ code in a programmatic transaction (for example from a place where you cannot use AOP), use api:configuration.jooq.JooqTransactionOperations[].
It will execute the callback inside a Micronaut-managed JDBC transaction and provide a transaction-scoped link:{jooqapi}/org/jooq/DSLContext.html[DSLContext].

[source,java]
----
// Injected bean (one per datasource)
private final JooqTransactionOperations txOps;

public int example() {
    return txOps.execute(ctx -> ctx.selectOne().fetchSingle(0, Integer.class));
}
----

